import { Layout } from '@layouts/Layout';
import Head from 'next/head';

const Home = () => (
  <>
    <Head>
      <title>Mercado Libre</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <Layout>
      <span>... placeholder text</span>
    </Layout>
  </>
);

export default Home;
